# Teste do módulo 2

1. Use o conjunto de dados EDHEC Hedge Fund Indexes que usamos na tarefa de laboratório, bem como nas tarefas da semana anterior. Carregue-os no Python e execute a seguinte análise com base nos dados desde 2000 (incluindo todo o ano de 2000): Qual foi o VaR Gaussiano Paramétrico Mensal no nível de 1% (como um número +ve) da estratégia Distressed Securities?

    Insira o número positivo como uma porcentagem, por exemplo. Para 5,32% insira 5,32

    NOTA: Você pode arredondar ou truncar para 1 casa decimal, aceitaremos qualquer resposta

In [2]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import risk_toolkit as rt 


In [3]:
hfi = rt.get_hfi_returns()
hfi.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
1997-01                 0.0119      0.0393                 0.0178   
1997-02                 0.0123      0.0298                 0.0122   
1997-03                 0.0078     -0.0021                -0.0012   
1997-04                 0.0086     -0.0170                 0.0030   
1997-05                 0.0156     -0.0015                 0.0233   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
1997-01            0.0791                 0.0189        0.0213   
1997-02            0.0525                 0.0101        0.0084   
1997-03           -0.0120                 0.0016       -0.0023   
1997-04            0.0119                 0.0119       -0.0005   
1997-05            0.0315                 0.0189        0.0346   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
1997-01                  0.0191        0.0573             0.0281   
1997-02                  0.0122        0.0175            -0.0006   
1997-03                  0.0109       -0.0119            -0.0084   
1997-04                  0.0130        0.0172             0.0084   
1997-05                  0.0118        0.0108             0.0394   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
1997-01            0.0150          0.0180        -0.0166          0.0317  
1997-02            0.0034          0.0118         0.0426          0.0106  
1997-03            0.0060          0.0010         0.0778         -0.0077  
1997-04           -0.0001          0.0122        -0.0129          0.0009  
1997-05            0.0197          0.0173        -0.0737          0.0275

In [4]:
hfi2000 = hfi['2000':]
hfi2000.head()

Convertible Arbitrage  CTA Global  Distressed Securities  \
date                                                                
2000-01                 0.0227      0.0128                 0.0088   
2000-02                 0.0267     -0.0022                 0.0421   
2000-03                 0.0243     -0.0138                 0.0103   
2000-04                 0.0223     -0.0241                -0.0101   
2000-05                 0.0149      0.0114                -0.0132   

         Emerging Markets  Equity Market Neutral  Event Driven  \
date                                                             
2000-01            0.0077                 0.0075        0.0088   
2000-02            0.0528                 0.0253        0.0346   
2000-03            0.0318                 0.0134        0.0069   
2000-04           -0.0541                 0.0168       -0.0059   
2000-05           -0.0433                 0.0062       -0.0034   

         Fixed Income Arbitrage  Global Macro  Long/Short Equity  \
date                                                               
2000-01                  0.0041        0.0021             0.0075   
2000-02                  0.0097        0.0408             0.0699   
2000-03                 -0.0061       -0.0104             0.0006   
2000-04                 -0.0006       -0.0304            -0.0201   
2000-05                  0.0107       -0.0070            -0.0097   

         Merger Arbitrage  Relative Value  Short Selling  Funds Of Funds  
date                                                                      
2000-01            0.0143          0.0173         0.0427          0.0169  
2000-02            0.0239          0.0185        -0.1340          0.0666  
2000-03            0.0131          0.0163        -0.0230          0.0039  
2000-04            0.0188          0.0092         0.1028         -0.0269  
2000-05            0.0146          0.0080         0.0704         -0.0122

Para a estratégia "Distressed Securities", o Valor em Risco ($VaR$) ao nível de significância de 1% é:

In [5]:
r = hfi2000['Distressed Securities'].head()
var1 = rt.var_gaussian(r, 1)
print(f"VaR = {100 * var1:.2f}%")

VaR = 3.83%


2. Use o mesmo conjunto de dados da pergunta anterior. Qual foi o VaR de 1% para a mesma estratégia após a aplicação do Ajuste Cornish-Fisher?

    Digite a resposta como um número positivo, em termos percentuais. por exemplo. para 5,32% digite 5,32

Aplicando o ajuste de Cornish-Fisher, o Valor em Risco ao nível de 1% para a estratégia "Distressed Securities" é:

In [6]:
var2 = rt.var_gaussian(r, 1, modified=1)
print(f"VaR Cornish-Fisher = {100 * var2:.2f}%")

VaR Cornish-Fisher = 2.84%


3. Use o mesmo conjunto de dados da pergunta anterior. Qual foi o VaR Histórico Mensal ao nível de 1% (como um número +ve) da estratégia Distressed Securities?

In [7]:
var3 = rt.var_historic(r, level=1)
print(f"VaR Histórico = {100 * var3:.2f}%")

VaR Histórico = 1.31%


4. Em seguida, carregue os 30 dados de retorno do setor usando a função `erk.get_ind_returns()` que desenvolvemos durante as sessões de laboratório. Para fins das demais perguntas, use dados durante o período de 5 anos 2013-2017 (ambos inclusive) para estimar os retornos esperados, bem como a matriz de covariância. Para poder responder às perguntas, você precisará construir os portfólios MSR, EW e GMV consistindo nas indústrias "Books", "Steel", "Oil" e "Mines". Suponha que a taxa livre de risco durante o período de 5 anos seja de 10%.

     Qual é o peso do Aço no Portfólio EW?

In [8]:
port30 = rt.get_ind_returns()
port30 = port30['2013':'2018']
port30.head()

Food    Beer   Smoke   Games   Books   Hshld   Clths    Hlth  \
2013-01  0.0554  0.0507  0.0561  0.1313  0.0513  0.0869  0.0256  0.0807   
2013-02  0.0384  0.0522  0.0221  0.0000 -0.0654  0.0314  0.0146  0.0135   
2013-03  0.0656  0.0531  0.0272  0.0769  0.0778  0.0219  0.0288  0.0651   
2013-04  0.0284  0.0355  0.0440  0.0451 -0.0029  0.0135  0.0903  0.0259   
2013-05 -0.0345 -0.0147 -0.0298  0.0218  0.0479 -0.0022  0.0078  0.0163   

          Chems   Txtls  ...   Telcm   Servs   BusEq   Paper   Trans   Whlsl  \
2013-01  0.0506  0.0922  ...  0.0495  0.0663 -0.0118  0.0561  0.0852  0.0646   
2013-02 -0.0095  0.0570  ...  0.0221  0.0097  0.0026  0.0463  0.0364  0.0207   
2013-03  0.0121  0.0888  ...  0.0577  0.0245  0.0319  0.0553  0.0465  0.0325   
2013-04  0.0396  0.0102  ...  0.0420  0.0184 -0.0102 -0.0002 -0.0014  0.0017   
2013-05  0.0343  0.0077  ... -0.0171  0.0363  0.0551  0.0221  0.0274  0.0385   

          Rtail   Meals     Fin   Other  
2013-01  0.0541  0.0523  0.0632  0.0720  
2013-02  0.0061  0.0070  0.0129  0.0443  
2013-03  0.0477  0.0550  0.0453  0.0228  
2013-04  0.0320  0.0240  0.0157  0.0074  
2013-05  0.0239 -0.0030  0.0708  0.0590  

[5 rows x 30 columns]

In [9]:
port30.columns

Index(['Food', 'Beer', 'Smoke', 'Games', 'Books', 'Hshld', 'Clths', 'Hlth',
       'Chems', 'Txtls', 'Cnstr', 'Steel', 'FabPr', 'ElcEq', 'Autos', 'Carry',
       'Mines', 'Coal', 'Oil', 'Util', 'Telcm', 'Servs', 'BusEq', 'Paper',
       'Trans', 'Whlsl', 'Rtail', 'Meals', 'Fin', 'Other'],
      dtype='object')

In [10]:
l = ["Books", "Steel", "Oil", "Mines"]
er = rt.annualize_rets(port30[l], 12)
cov = port30[l].cov()

In [11]:
n = er.shape[0]
w_ew = np.repeat(1/n, n)
w_ew

array([0.25, 0.25, 0.25, 0.25])

5. Qual é o peso do maior componente do portfólio MSR?

In [12]:
rf = 0.1
w_msr = rt.msr(rf, er, cov)
w_msr

array([1.49880108e-15, 1.00000000e+00, 2.17187379e-15, 3.91353616e-15])

In [13]:
max(w_msr)

0.9999999999999925

6. Qual dos 4 componentes tem o maior peso no portfólio MSR?

Steel

7. Quantos dos componentes do portfólio MSR têm pesos diferentes de zero?

Apenas 1

8. Qual é o peso da maior componente da carteira GMV?

In [14]:
rf = 0.1
w_gmv = rt.gmv(cov)
w_gmv

array([5.10061017e-01, 1.14925430e-17, 3.40468524e-01, 1.49470459e-01])

In [15]:
max(w_gmv)

0.5100610168492838

In [16]:
dict(zip(l, w_gmv))

{'Books': 0.5100610168492838,
 'Steel': 1.1492543028346347e-17,
 'Oil': 0.3404685237878173,
 'Mines': 0.14947045936289885}

9. Qual das 4 componentes tem o maior peso no portefólio da GMV?

Books

10. Quantos componentes da carteira GMV têm pesos diferentes de zero?

3

11. Suponha que dois investidores diferentes investiram nas carteiras GMV e MSR no início de 2018 usando os pesos que acabamos de calcular. Calcule a volatilidade anualizada dessas duas carteiras nos próximos 12 meses de 2018? (Dica: use o código portfolio_vol que desenvolvemos no laboratório e use ind[“2018”][l].cov() para calcular a matriz de covariância para 2018, assumindo que a variável ind contém os retornos da indústria e a variável l mantém o lista de portfólios do setor que você está disposto a manter. Não se esqueça de anualizar a volatilidade)

    Qual seria a volatilidade anualizada ao longo de 2018 usando os pesos da carteira MSR?

In [20]:
ind = rt.get_ind_returns()
ind.head()

Food    Beer   Smoke   Games   Books   Hshld   Clths    Hlth  \
1926-07  0.0056 -0.0519  0.0129  0.0293  0.1097 -0.0048  0.0808  0.0177   
1926-08  0.0259  0.2703  0.0650  0.0055  0.1001 -0.0358 -0.0251  0.0425   
1926-09  0.0116  0.0402  0.0126  0.0658 -0.0099  0.0073 -0.0051  0.0069   
1926-10 -0.0306 -0.0331  0.0106 -0.0476  0.0947 -0.0468  0.0012 -0.0057   
1926-11  0.0635  0.0729  0.0455  0.0166 -0.0580 -0.0054  0.0187  0.0542   

          Chems   Txtls  ...   Telcm   Servs   BusEq   Paper   Trans   Whlsl  \
1926-07  0.0814  0.0039  ...  0.0083  0.0922  0.0206  0.0770  0.0193 -0.2379   
1926-08  0.0550  0.0814  ...  0.0217  0.0202  0.0439 -0.0238  0.0488  0.0539   
1926-09  0.0533  0.0231  ...  0.0241  0.0225  0.0019 -0.0554  0.0005 -0.0787   
1926-10 -0.0476  0.0100  ... -0.0011 -0.0200 -0.0109 -0.0508 -0.0264 -0.1538   
1926-11  0.0520  0.0311  ...  0.0163  0.0377  0.0364  0.0384  0.0160  0.0467   

          Rtail   Meals     Fin   Other  
1926-07  0.0007  0.0187  0.0037  0.0520  
1926-08 -0.0075 -0.0013  0.0446  0.0676  
1926-09  0.0025 -0.0056 -0.0123 -0.0386  
1926-10 -0.0220 -0.0411 -0.0516 -0.0849  
1926-11  0.0652  0.0433  0.0224  0.0400  

[5 rows x 30 columns]

In [24]:
l = ["Books", "Steel", "Oil", "Mines"]
ind2018 = ind['2018']
er = rt.annualize_rets(ind2018[l], 12)
er

/tmp/ipykernel_1220/240627046.py:2: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  ind2018 = ind['2018']


Books   -0.252523
Steel   -0.273127
Oil     -0.181373
Mines   -0.307972
dtype: float64

In [25]:
cov = ind["2018"][l].cov()
cov

/tmp/ipykernel_1220/2544816361.py:1: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  cov = ind["2018"][l].cov()


Books     Steel       Oil     Mines
Books  0.002799  0.002098  0.002558  0.001629
Steel  0.002098  0.004027  0.003473  0.001843
Oil    0.002558  0.003473  0.005296  0.001961
Mines  0.001629  0.001843  0.001961  0.002059

In [26]:
rf = 0.1
w_msr = rt.msr(rf, er, cov)
w_msr

array([2.47024623e-15, 0.00000000e+00, 1.00000000e+00, 9.85322934e-15])

In [28]:
vol = rt.portfolio_vol(w_msr, cov)
print(f"{100 * vol:.2f}%")

7.28%


12. Qual seria a volatilidade anualizada ao longo de 2018 usando os pesos da carteira GMV? (Lembrete e dica: use o código portfolio_vol que desenvolvemos no laboratório e use ind[“2018”][l].cov() para calcular a matriz de covariância para 2018, assumindo que a variável ind contém os retornos do setor e a variável l contém a lista de portfólios do setor que você deseja manter. Não se esqueça de anualizar a volatilidade)

In [31]:
l = ["Books", "Steel", "Oil", "Mines"]
ind2018 = ind['2018']
er = rt.annualize_rets(ind2018[l], 12)
cov = ind["2018"][l].cov()

rf = 0.1
w_gmv = rt.gmv(cov)

vol = rt.portfolio_vol(w_gmv,cov)
print(f"{100 * vol:.2f}%")

4.41%


/tmp/ipykernel_1220/3712161638.py:2: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  ind2018 = ind['2018']
/tmp/ipykernel_1220/3712161638.py:4: FutureWarning: Indexing a DataFrame with a datetimelike index using a single string to slice the rows, like `frame[string]`, is deprecated and will be removed in a future version. Use `frame.loc[string]` instead.
  cov = ind["2018"][l].cov()
